# Serverless config for deployment to AWS Lambda: docs.serverless.com

frameworkVersion: '2'
service: FoodWebJobs
app: foodweb
org: marknemm

# Custom variables that may be referenced within this file.
custom:
  stage: ${opt:stage, self:provider.stage}

# AWS provider details used for deployment, and global config shared among all Lambda Functions.
provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment: ${file(.env.yml):}
  timeout: 900 # Maximum - 15 minutes timeout.
  vpc:
    securityGroupIds:
      - sg-08c2d5030e060406c
    subnetIds:
      - subnet-1e1ab175
      - subnet-d37e369f
      - subnet-5e806023
  layers: # Layers shared among all Lambda Functions.
    - { Ref: CoreDependenciesLambdaLayer }
    - { Ref: GeoTzDependenciesLambdaLayer }

# Package config which details patterns of directories/files to include & exclude in each Lambda Function.
package:
  patterns:
    # Exclude all - specify include overrides below.
    - '!**'
    # Auto-generated serverless platform include(s).
    - 's_*'
    - 'serverless_sdk/*'
    # Top level project include(s).
    - 'package.json'
    # Server project include(s).
    - 'server/dist/**'
    - 'server/projects/jobs/**'
    - 'server/projects/web/**'
    - 'server/templates/**'
    - 'server/package.json'
    - 'server/tsconfig.base.json'
    - 'server/tsconfig.json'
    # Shared project include(s).
    - 'shared/src/web/**'
    - 'shared/package.json'
    - 'shared/tsconfig.json'

layers:
  CoreDependencies:
    path: server/lambda-layers/core-dependencies
    description: Core node module dependencies
    compatibleRuntimes:
      - nodejs14.x
    package:
      patterns:
        - 'nodejs/**'
  GeoTzDependencies:
    path: server/lambda-layers/geo-tz-dependencies
    description: Geo timezone node module dependencies
    compatibleRuntimes:
      - nodejs14.x
    package:
      patterns:
        - 'nodejs/**'

functions:
  AutoAssignDonations:
    handler: server/dist/server/projects/jobs/src/index.handler
    description: Auto assigns unclaimed donations to an eligible receiver organization
    environment:
      JOB_NAME: auto-assign-donations
    events:
      - schedule: cron(*/10 * * * ? *) # Run every 10th minute of hour (eg. 1:00, 1:10, 1:20, 1:30, 1:40, 1:50, 2:00, etc...)
  DeletePasswordReset:
    handler: server/dist/server/projects/jobs/src/index.handler
    description: Deletes all password reset tokens older than 5 minutes
    environment:
      JOB_NAME: delete-password-reset
    events:
      - schedule: cron(*/10 * * * ? *) # Run every 10th minute of hour (eg. 1:00, 1:10, 1:20, 1:30, 1:40, 1:50, 2:00, etc...)
  SendDeliveryReminders:
    handler: server/dist/server/projects/jobs/src/index.handler
    description: Sends delivery reminders to all parties associated with a donation delivery 24 hours and 1 hour before delivery window start
    environment:
      JOB_NAME: send-delivery-reminders
    events:
      - schedule: cron(*/10 * * * ? *) # Run every 10th minute of hour (eg. 1:00, 1:10, 1:20, 1:30, 1:40, 1:50, 2:00, etc...)
  SendDonationHubReminders:
    handler: server/dist/server/projects/jobs/src/index.handler
    description: Sends donation hub drop-off reminders to all parties associated with a donation hub 24 hours and 1 hour before drop-off window start
    environment:
      JOB_NAME: send-donation-hub-reminders
    events:
      - schedule: cron(*/10 * * * ? *) # Run every 10th minute of hour (eg. 1:00, 1:10, 1:20, 1:30, 1:40, 1:50, 2:00, etc...)
