# Serverless config for deployment to AWS Lambda: docs.serverless.com

frameworkVersion: '^3.1.0'
service: FoodWebJobs
app: foodweb
org: marknemm

# Custom variables that may be referenced within this file.
custom:
  stage: ${opt:stage, self:provider.stage}

# AWS provider details used for deployment, and global config shared among all Lambda Functions.
provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
  timeout: 900 # Maximum - 15 minutes timeout.
  vpc:
    securityGroupIds:
      - sg-0888b39f430dedfd8 # Access to DB & ElastiCache within VPC.
    subnetIds:
      - subnet-0490e7d052f348602 # lambda-private-1 (subnet) -> lambda-public-1 (subnet) -> NAT Gateway 1 -> Internet Gateway
      - subnet-084c9968678eee263 # lambda-private-2 (subnet) -> lambda-public-2 (subnet) -> NAT Gateway 2 -> Internet Gateway
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess # Create basic lambda iam role with policy to read SSM Param Store for env vars.
  ecr:
    images:
      foodweb-jobs:
        path: .
        file: ./server/projects/jobs/Dockerfile # Jobs Dockerfile is separate from top-level development Dockerfile.

functions:
  AutoAssignDonations:
    description: Auto assigns unclaimed donations to an eligible receiver organization
    image:
      name: foodweb-jobs
    environment:
      JOB_NAME: auto-assign-donations
      PRODUCTION: true
    events:
      - schedule: cron(*/10 * * * ? *) # Run every 10th minute of hour (eg. 1:00, 1:10, 1:20, 1:30, 1:40, 1:50, 2:00, etc...)
  DeletePasswordReset:
    description: Deletes all password reset tokens older than 5 minutes
    image:
      name: foodweb-jobs
    environment:
      JOB_NAME: delete-password-reset
      PRODUCTION: true
    events:
      - schedule: cron(*/10 * * * ? *) # Run every 10th minute of hour (eg. 1:00, 1:10, 1:20, 1:30, 1:40, 1:50, 2:00, etc...)
  SendDeliveryReminders:
    description: Sends delivery reminders to all parties associated with a donation delivery 24 hours and 1 hour before delivery window start
    image:
      name: foodweb-jobs
    environment:
      JOB_NAME: send-delivery-reminders
      PRODUCTION: true
    events:
      - schedule: cron(*/10 * * * ? *) # Run every 10th minute of hour (eg. 1:00, 1:10, 1:20, 1:30, 1:40, 1:50, 2:00, etc...)
  SendDonationHubReminders:
    description: Sends donation hub drop-off reminders to all parties associated with a donation hub 24 hours and 1 hour before drop-off window start
    image:
      name: foodweb-jobs
    environment:
      JOB_NAME: send-donation-hub-reminders
      PRODUCTION: true
    events:
      - schedule: cron(*/10 * * * ? *) # Run every 10th minute of hour (eg. 1:00, 1:10, 1:20, 1:30, 1:40, 1:50, 2:00, etc...)
